--- #sudo pip install boto
- name: Creates ec2 instances
  hosts: localhost
  tasks:
    - name: Creates CentOS7 instance
      ec2:
        key_name: "{{key_name}}"      
        instance_type: "{{instance_type}}"
        image: "{{centos7_image}}"
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        region: "{{region}}"
