---
- name: Installs ncpa agent on instances
  hosts: all
  become: yes
  become_user: root
  tasks: 
    - name: Create Repo on Centos6
      when: ansible_distribution == "CentOS" and ansible_distributio_major_version == "6"
      shell: "rpm -Uvh http://repo.nagios.com/nagios/6/nagios-repo-6-3.el6.noarch.rpm"

    - name: Install ncpa on centos6
      package: 
        name: ncpa
        state: present
      notify: NCPA_CENTOS_6  

    - name: Change the code inside ncpa.cfg
      when: ansible_distribution == "CentOS" and ansible_distributio_major_version == "6"
      lineinfile: 
        path: /usr/local/ncpa/etc/ncpa.cfg
        regexp: "community_string = mytoken" 
        line: "xommunity_string = STRONGPASSWORD" 




    - name: Create repo on Centos7
      when: ansible_distribution == "CentOS" and ansible_distributio_major_version == "7"
      shell: "rpm -Uvh http://repo.nagios.com/nagios/7/nagios-repo-7-3.el7.noarch.rpm"

    - name: Install ncpa on Centos7 
      when: ansible_distribution == "CentOS" and ansible_distributio_major_version == "7"
      package: 
        name: ncpa
        state: present   
      notify: NCPA_CENTOS_7      

    - name: Change the code inside ncpa.cfg
      when: ansible_distribution == "CentOS" and ansible_distributio_major_version == "7"
      lineinfile: 
        path: /usr/local/ncpa/etc/ncpa.cfg
        regexp: "community_string = mytoken" 
        line: "xommunity_string = STRONGPASSWORD"   

  hadlers: 
    - name: NCPA_CENTOS_6
      service:
        name: ncpa_listener  
        state: restarted   

    - name: NCPA_CENTOS_7
      systemd:
        name: ncpa_listener  
        state: restarted        