---
- name: Terminate Instances
  hosts: localhost
  tasks: 
    - name: Terminate instances
      ec2:
        instance_ids: "{{ID}}"
        state: absent #stopped #started
        region: "{{REGION}}"