---
- name: Internet gate way
  hosts: localhost 
  vars_files:
    - var_igw
  tasks:
    - name: Create internet gate way
      ec2_vpc_igw:
        vpc_id: "{{vpc_id}}"
        region: "{{region}}"
        state: present
      register: igw