--- #sudo pip install boto
- name: Creates ec2 instances
  hosts: localhost
  vars_files:
    - ec2vars
  tasks:
    - name: Creates CentOS7 instance
      ec2:
        key_name: "{{key_name}}"      
        instance_type: "{{instance_type}}"
        image: "{{centos7_image}}"
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        region: "{{region}}"
        instance_tags:
          Name: Centos_7-{{ item }}
        assign_public_ip: yes
        wait: yes
      loop: "{{ range(1, 5 + 1)| list }}"
      
      


  # vars_files:
  #   - ec2vars_Debian_GNU
    - name: Creates Fedora instance
      ec2:
        key_name: "{{key_name}}"      
        instance_type: "{{instance_type}}"
        image: "{{fedora_image}}"
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        region: "{{region}}"
        instance_tags:
          Name: Fedora-{{ item }}
        assign_public_ip: yes
        wait: yes
        user_data:
          #!/bin/sh
          sudo apt-get install python -y
          sudo pip install boto
      loop: "{{ range(1, 3 + 1)| list }}"
      
      
      


  # vars_files:
  #   - ec2vars_CentOS_6
    - name: Creates CentOS_6 instance
      ec2:
        key_name: "{{key_name}}"      
        instance_type: "{{instance_type}}"
        image: "{{centos6_image}}"
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        region: "{{region}}"
        instance_tags:
          Name: CentOS_6-{{ item }}
        assign_public_ip: yes
        wait: yes
        user_data:
          #!/bin/sh
          sudo apt-get install python -y
          sudo pip install boto
      loop: "{{ range(1, 2 + 1)| list }}"